services:
  web:
    image: abcniku/django:web
    # build: hello_django
    restart: always
    command: sh -c "python manage.py flush --no-input && python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser --noinput && gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000"

    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SECRET_KEY=django-insecure-cq076cy4v=^&=h@unjgkjqd(p%5^h3!k&mfq@1h(0qjgs&)y33
      - DEBUG=0
    volumes:
      - ./hello_django/:/usr/src/hello_django/
      - ./hello_django/static/:/usr/src/hello_django/static/
    expose:
      - 80
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    healthcheck:
      test: "pg_isready -U hello_django -d hello_django_dev"
      interval: 1s
      timeout: 2s
      retries: 5
  nginx:
    image: abcniku/django:nginx
    # build: nginx
    ports:
      - "1337:80"
    volumes:
      - ./hello_django/static/:/usr/src/hello_django/static/
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: